# Generated by Django 4.2 on 2023-04-09 07:31

from django.db import migrations, models
import django.utils.timezone
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, null=True, upload_to=uploads.models.upload_to)),
                ('uploadtime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
